language: ruby
rvm:
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
  - 2.0.0
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - kbedell@gmail.com
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
    - rvm: 2.0.0